# Netlify configuration for static portfolio
[build]
  publish = "."
  command = ""

# Enable pretty URLs
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self' https://unpkg.com https://unpkg.com/@babel/standalone 'unsafe-eval'; connect-src 'self' ws: wss:;"
